OPNDLG-330 Dynamic Attributes
opendialogai/core pull request #428
Opened 2021-01-26 14:24 UTC by bendeeson

Adds the ability to define attributes dynamically in the database instead of only in config files.

Adds a new Laravel Model 'Dynamic Attribute' which stores an attribute id (unique snake_case string) and attribute type (attribute.core.<name>) in the database. Includes two regex patterns to check the format of the attribute id and type.

2021-01-27 11:54 UTC, elliotmassen requested changes
This looks good, nice one 👍  Just a few thoughts below. Once addressed, I suppose we could either merge this without the integration with `ContextEngine` (or `AttributeEngine` if #429 is merged), or add the integration to this PR. I'm thinking it'd be better to do the integration in a new PR so that we can get this merged and keep things moving.

2021-01-27 11:54 UTC, elliotmassen commented on src/DynamicAttribute.php
> +    public $timestamps = false;
I think it might be worth having the `created_at` & `updated_at` timestamps enabled, it may be useful for the UI in the near future.

2021-01-27 11:54 UTC, elliotmassen commented on database/migrations/2021_01_22_160714_create_dynamic_attributes_table.php
> +            $table->primary('id');
I'm thinking that it might be better to use an auto-incrementing int ID as the primary key. As we want each attribute to be granularly editable, I can imagine a scenario in which a user changed the name of an attribute and if we are using the name as the key, that may introduce issues with querying/routing. Let me know what you think - I might be overthinking it.

2021-01-27 11:54 UTC, elliotmassen commented on src/DynamicAttribute.php
> +    static private $validTypePattern = "/^attribute\.[A-Za-z]*\.[A-Za-z_]*$/";
Do you think it might be worth moving these patterns to the `AttributeResolver`? I'm looking at how we do it for interpreters and we have a similar `$validNamePattern` in the `InterpreterService`. Perhaps we get to the "contracts" work these patterns will even live there.

2021-01-28 12:59 UTC, bendeeson commented on database/migrations/2021_01_22_160714_create_dynamic_attributes_table.php
> +            $table->primary('id');
Yes, I can see the value in having a stable ID for routing purposes. I'll change the `id` column to be the auto-incrementing and add a unique string `attribute_id` for the actual attribute id. The name `attribute_id` feels a bit clumsy, so let me know if have something else in mind.

2021-01-28 13:01 UTC, bendeeson commented on src/DynamicAttribute.php
> +    public $timestamps = false;
I this case I'd prefer to wait until theres a use case, and then alter the schema to suit. It would be especially confusing in the future if there are a `created_at` and `updated_at` columns, but the don't get used for anything.

2021-01-28 14:23 UTC, elliotmassen commented on database/migrations/2021_01_22_160714_create_dynamic_attributes_table.php
> +            $table->primary('id');
Perhaps `attribute_name`?

2021-01-29 10:17 UTC, stu-greenshoots commented on src/DynamicAttribute.php
> +    public $timestamps = false;
I'm inclined to agree with @elliotmassen as we use these throughout our schema currently. I could see why an updated_at might need a use case to be useful (and arguably we'd need an activity log type thing for this case), but being able to display when the dynamic attribute was added on the UI seems like something we'd want

2021-02-02 10:07 UTC, elliotmassen approved these changes
This looks good to me! As discussed, I'll leave with you to handle merging/branching of this as you see fit.

2021-02-03 11:45 UTC, elliotmassen commented
Closing in favour of #433.

2021-02-03 11:45 UTC, closed without merging