Feature/opndlg 344  integrate dynamic attributes with attribute engine
opendialogai/core pull request #433
Opened 2021-02-02 18:34 UTC by bendeeson

Introduces the 'Dynamic attributes' concept. Dynamic attributes are (attribute id, attribute type) pairs stored in the database. They allow for defining attributes outside of configuration files.
This PR introduces a new DynamicAttribute laravel model to the attribute engine and integrates it into the attribute resolver.

2021-02-03 14:25 UTC, elliotmassen requested changes
Thanks for this! Please see my comments below regarding rethinking the registration of the dynamic attributes to be more consistent with existing registrations.

2021-02-03 14:25 UTC, elliotmassen commented on src/AttributeEngine/Facades/AttributeResolver.php
> + * @method static void registerAllDynamicAttributes()
Let's move this functionality into the `AttributeEngineServiceProvider`, the resolver should be fairly agnostic to the source of attributes. I'll leave further comments on the service provider file.

2021-02-03 14:25 UTC, elliotmassen commented on src/AttributeEngine/Tests/AttributeResolverServiceTest.php
> +    use RefreshDatabase;
I think our test suite should be doing this automatically before each test - did you encounter an issue relating to this?

2021-02-03 14:34 UTC, elliotmassen requested changes
Ah my last review lost some of my comments - I've rewritten them and added to this review.

2021-02-03 14:34 UTC, elliotmassen commented on src/AttributeEngine/AttributeEngineServiceProvider.php
> +            $attributeResolver->registerAllDynamicAttributes();
I think we should keep this consistent with existing attribute registration (as seen with core and app attributes above), with something similar to:

```suggestion
            if ($this->hasDynamicAttributes()) {
                $attributeResolver->registerAttributes($this->formatDynamicAttributes());
            }
```

This way the resolver remains fairly agnostic to the source of registered attributes. The outcome of this change is to create some `formatDynamicAttributes` method that can retrieve dynamic attributes from the database and map them the same format as found in the config files:

```php
[
    'my_custom_str_attr' => StringAttribute::class,
    'my_custom_bool_attr' => BooleanAttribute::class,
    ...
]
```

For this we can make use of `AttributeTypeService.getAttributeTypeClass` to turn attribute type IDs (eg. `attribute.core.string`) into attribute type classes (eg. `StringAttribute::class`).

2021-02-03 14:34 UTC, elliotmassen commented on src/AttributeEngine/AttributeResolver/AttributeResolver.php
> +        }
Some of these checks already exist in the `registerAttributes` method above, and others would be better placed in the service provider. Please see my comment in the service provider file for how we can look to remove this method.

2021-02-08 08:25 UTC, bendeeson commented on src/AttributeEngine/AttributeEngineServiceProvider.php
> +            $attributeResolver->registerAllDynamicAttributes();
This has been updated.

2021-02-08 19:08 UTC, elliotmassen approved these changes
This ready to merge, but I'd imagine we'll want to get #435 merged first, as it contains parts of #434 as does this PR.

2021-02-15 17:45 UTC, merged