Reflection API
opendialogai/core pull request #434
Opened 2021-02-03 18:53 UTC by elliotmassen

2021-02-06 09:45 UTC, istos commented
@elliotmassen I went ahead and merged this in my attribute-1x branch so that I can work on top of what you have. Apologies for the heavy-handedness of it but This should avoid a world of pain for you trying to merge later. Once you've checked the changes in attribute-1x you can then branch of that to continue work and we could close this.

2021-02-17 07:27 UTC, istos requested changes
All looks good - my only blocking question is around making the UserContext dependent on the UserDataClient rather than a more generic ContextDataClient contract.

2021-02-17 07:27 UTC, istos commented on src/AttributeEngine/AttributeResolver/AttributeResolver.php
> +    /** @var Map|AttributeDeclaration */
Now that we have introduced Laravel Collections in the conversation model I would default to using collections anywhere we might think of using Map - especially in places where we were not using Map already.

2021-02-17 07:27 UTC, istos commented on src/AttributeEngine/AttributeResolver/AttributeDeclaration.php
> +class AttributeDeclaration
Some comment here explaining what an AttributeDeclaration is.

2021-02-17 07:27 UTC, istos commented on src/ContextEngine/Contexts/User/UserContext.php
> +    public function __construct(UserDataClient $dataClient)
I am not sure that the UserContext needs to be aware of the fact that it is using anything other that a ContextDataClient - this will save us from introducing customized functionality in the UserDataClient that then the UserContext becomes dependent on.

2021-02-17 10:07 UTC, elliotmassen commented on src/ContextEngine/Contexts/User/UserContext.php
> +    public function __construct(UserDataClient $dataClient)
Ah yes, my bad I should've explained why I did this. While I was doing this work I figured that the Context engine could be standardised a bit and made it so that even core contexts are registered via a configuration array:

https://github.com/opendialogai/core/blob/ad31fa96c2dd654f9e371b2411fd5a0b85c530d6/src/ContextEngine/ContextEngineServiceProvider.php#L23-L33

This removed the ability to directly pass parameters to the constructor, and therefore the solution was to lean on Laravel's dependency injection here. As we're using `resolve()` it will automatically pass in the `UserDataClient` for us. But to be able to do this it requires the bound class name to resolve against, hence the change to `UserDataClient`. I was thinking that as the parent `PersistentContext` constructor still retains the more general `ContextDataClient` that it still gives us that flexibility.

https://github.com/opendialogai/core/blob/ad31fa96c2dd654f9e371b2411fd5a0b85c530d6/src/ContextEngine/ContextService/CoreContextService.php#L111-L115

I definitely take your point though, and I'm happy to revert the change if you'd like. My argument in favour of keeping it (perhaps with adjustments) is that we will likely need to be able to parameterise the constructors of custom contexts which will require the same considerations.

2021-02-17 10:23 UTC, istos commented on src/ContextEngine/Contexts/User/UserContext.php
> +    public function __construct(UserDataClient $dataClient)
Got it. Ok - let's leave it as is for now. Might make sense to get a feel for what else might come up and whether we do need to do something different in the future 👍

2021-02-17 10:24 UTC, istos approved these changes

2021-02-17 17:55 UTC, merged