ActionPerformer
opendialogai/core pull request #445
Opened 2021-02-19 13:37 UTC by elliotmassen

This PR adds an `ActionPerformer` class that:

 - defines methods that take input of `Intent`(s) or `Action`(s),
 - provide the actions with the desired attribute inputs,
 - perform the associated actions,
 - take the actions result attributes and store them in the desired contexts,
 - and persists any updated persistent contexts.

2021-02-19 13:37 UTC, elliotmassen commented on src/ConversationEngine/Tests/ActionPerformerTest.php
> +    }
This test is failing currently, I think it may require some related work in the context or attribute engine.

2021-02-19 13:52 UTC, elliotmassen commented on phpunit.xml
> +        </testsuite>
I've updated this more of the test suite configuration, to give us a way of iteratively expanding the ConversationEngine tests, while excluding more holistic tests until later.

2021-02-19 15:40 UTC, istos requested changes
Looking good @elliotmassen 👍 - main thing for me would be the Facade to access that ActionEngineInterface implementation instead of the Laravel resolve() function

2021-02-19 15:40 UTC, istos commented on src/ConversationEngine/Reasoners/ActionPerformer.php
> +        $actionResult = resolve(ActionEngineInterface::class)->performAction(
Could we do a Facade from the ActionEngineInterface so that we have a consistent way of accessing engines (always through Facades)

2021-02-19 15:40 UTC, istos commented on src/ConversationEngine/Reasoners/ActionPerformer.php
> +            $context->addAttribute($attribute);
This is saving directly to the context and not going through the AttributeResolver which means we would be able to save attributes that are defined in the CDL of the app, but are not part of the supported attributes for the app?

2021-02-19 15:51 UTC, elliotmassen commented on src/ConversationEngine/Reasoners/ActionPerformer.php
> +            $context->addAttribute($attribute);
Hmm this is a good point - currently as the `ActionInterface` enforces each action to implement a `perform` method that returns an `ActionResult` (which holds an array of `Attribute`s - see below for the common factory method we use in actions), we give this control of resolving the attribute to each action.

As you say this means that the action could be instantiating attributes directly as opposed to running them through the resolver. I'm not sure how we'd get round this until we have actions returning `AttributeValue`'s as opposed to `Attribute`'s.

https://github.com/opendialogai/core/blob/f7771ec62f3dbe2a2eca5059883ff5711f690ed6/src/ActionEngine/Actions/ActionResult.php#L37-L46

2021-02-24 09:44 UTC, istos approved these changes

2021-02-24 10:04 UTC, merged