Feature/graphql client
opendialogai/core pull request #448
Opened 2021-02-26 14:52 UTC by bendeeson

Introduced a new 'GraphQL client' package.
This package includes a small DGraph GraphQL client that wraps Guzzle with some additional error checking as well as commands for setting the graphql schema and for wiping the the dgraph database.

2021-02-26 15:00 UTC, bendeeson commented on config/opendialog.php
>      'PACKAGE_NAME' => env('PACKAGE_NAME'),
Moved to GraphQLClient config

2021-02-26 15:03 UTC, bendeeson commented on src/GraphQLClient/config/opendialog-graphql.php
> +    }), "schema" => <<<'GQL'
This is the GraphQL schema to be passed to DGraph. It only contains types. DGraph generates the rest of the schema including data types etc from it.

2021-02-26 15:21 UTC, bendeeson commented on .circleci/config.yml
> +      - run: phpdbg -qrr ./vendor/bin/phpunit --exclude skip --no-coverage --configuration phpunit-ci.xml -d memory_limit=8192M
Uses a separate phpunit-ci.xml file now. This lets use remove the OVERWRITE_* env vars.

2021-02-26 16:07 UTC, elliotmassen commented on composer.json
> +    "opendialogai/dgraph-docker": "^20.11.0"
I'm not savvy with the requirements for this work, so please treat this as a question (to help my own understanding) rather than feedback: Is there a reason why this is re-introduced? I had presumed that when it was [removed](https://github.com/opendialogai/core/pull/435/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) in #435 that we would be mocking the client responses in tests and therefore we wouldn't require it as a dependency anymore. My understanding is definitely not 100% here, so I could well be missing something!!

2021-03-01 08:35 UTC, bendeeson commented on composer.json
> +    "opendialogai/dgraph-docker": "^20.11.0"
I agree that we should used mocked responses to speed up testing for the data-client. But I still wanted to have tests for the actual client to ensure that queries are being sent correctly, and that the functions for setting schema/dropping data work.

2021-03-01 08:37 UTC, bendeeson commented on src/GraphQLClient/config/opendialog-graphql.php
> +    name: String! @search(by:[hash])
This is the GraphQL schema to be passed to DGraph. It only contains types. DGraph generates the rest of the schema including data types etc from it.

2021-03-03 11:47 UTC, patshone-gsl commented on src/GraphQLClient/GraphQLClientServiceProvider.php
> +            $instanceType = config('opendialog.graphql.DGRAPH_INSTANCE_TYPE');
I wonder whether this logic might be better living outside of the service provider. I don't really know what the idiomatic laravel way of doing this would be - perhaps a client factory?

2021-03-03 11:48 UTC, patshone-gsl commented on src/GraphQLClient/Tests/SlashGraphQLEndpointTest.php
> +//    /**
Does the whole test need to be commented out here? - is the @group skip annotation not enough

2021-03-03 11:51 UTC, patshone-gsl commented on src/GraphQLClient/config/opendialog-graphql.php
> +    "schema" => <<<'GQL'
It feels like it would be better for this schema to live in a separate file rather than the config object. I'd be happier diffing if the changes to the schema itself were separate from changes to the config

2021-03-03 11:52 UTC, patshone-gsl requested changes
We should fix the commented test and move the schema into a separate file, but then I think this is good to go

2021-03-04 08:36 UTC, bendeeson commented on src/GraphQLClient/config/opendialog-graphql.php
> +    "schema" => <<<'GQL'
Makes sense. I'll factor the GraphQL into a separate file and load with `file_get_contents()`

2021-03-05 14:00 UTC, patshone-gsl approved these changes
Looks good

2021-03-05 14:00 UTC, merged