Incoming-outgoing intent matching: No-matching
opendialogai/core pull request #452
Opened 2021-03-12 17:01 UTC by elliotmassen

This PR implements functionality for when an incoming intent can not be matched. It's worth noting that ultimately if an incoming, or outgoing, intent can not be matched an empty intent collection will be returned (leaving us open to consider the best way to let the user know that something has gone wrong). In the case of incoming intents we have a desired process to attempt before this point however. This process breaks down as so.

**If the user is not in an ongoing conversation**:

1. Update the utterance's callback ID to `intent.core.NoMatch` and re-run incoming intent matching.

**If the user is in an ongoing conversation**:

1. Update the utterance's callback ID to `intent.core.TurnNoMatch` and re-run incoming intent matching.
2. Update the utterance's callback ID to `intent.core.SceneNoMatch` and re-run incoming intent matching.
3. Update the utterance's callback ID to `intent.core.ConversationNoMatch`, unset the user's current conversation and re-run incoming intent matching.
4. Update the utterance's callback ID to `intent.core.NoMatch`, unset the user's current conversation and re-run incoming intent matching.

2021-03-15 17:13 UTC, istos requested changes
A couple of small comments - love how concise all this can be 👍

2021-03-15 17:13 UTC, istos commented on src/ConversationEngine/Reasoners/IncomingIntentMatcher.php
> +    const GLOBAL_NO_MATCH_INTENT_ID = 'intent.core.NoMatch';
Is this a `SCENARIO_NO_MATCH` ?

2021-03-15 17:13 UTC, istos commented on src/ConversationEngine/Reasoners/IncomingIntentMatcher.php
> +            // It's a non-ongoing conversation
`// It's not an ongoing conversation`  <- this would be a clearer way of saying it, maybe?

2021-03-16 10:26 UTC, elliotmassen commented on src/ConversationEngine/Reasoners/IncomingIntentMatcher.php
> +    const GLOBAL_NO_MATCH_INTENT_ID = 'intent.core.NoMatch';
You could say that, I decided against it as at this point it represents a literal no-match (whereas you could say the others represent a no-match within a specific scope). I thought that naming it scenario no-match may confuse things as this is used for non-ongoing conversation requests too.

2021-03-16 10:30 UTC, elliotmassen commented on src/ConversationEngine/Reasoners/IncomingIntentMatcher.php
> +            // It's a non-ongoing conversation
Ha good point! I've now updated that.

2021-03-17 16:18 UTC, istos approved these changes

2021-03-17 16:22 UTC, merged