Feature/serializers
opendialogai/core pull request #454
Opened 2021-03-25 11:03 UTC by bendeeson

This PR adds support for serialization and deserialization of the core Conversation Objects (Scenario, Conversation, Scene, Turn, Intent) as well as various methods in ConversationDataClient.php to support this.

### Serialization

Serialization is performed using the Symphony Serialization package: https://symfony.com/doc/current/components/serializer.html
Custom Normalizers (src/Conversation/DataClients/Serializers) have been added for all core conversation objects, which convert a graph of conversation objects to/ from array representation.
The serialization format matches the shape of the GraphQL schema (See src/GraphQLClient/input_schema.gql).

### Conversation Data Client

The conversation data client has been updated with a number of methods to support storing/retrieving data from the graphql backend (DGraph). This is used by the Conversation Engine as well as the http APIs for all communication with DGraph. Methods generally take PHP Conversation Objects as arguments, and return them as results.

2021-03-26 10:54 UTC, elliotmassen reviewed
I've just had a skim through and commented on a few areas. Nothing major from me! It's also worth noting that I've been using certain aspects of this branch in my work in #453, and it's largely all worked as expected 👍 

My only main question is regarding new tests that actually communicate with the graph. I've noticed that the additions in this PR add about ~4/5 minutes to the CI pipeline length (up to ~ 7mins from 2mins). I'm wondering if this is the result of the testcases that extend `ConversationDataClientQueriesTest`? Apologies for raising this again! The few graph tests that were added in #448 didn't seem to have too much of an effect, but I'm wondering how necessary the new graph tests in this PR are (if they are in fact the culprit). My feeling is that at a certain point we are more so testing DGraph rather than our own code. Perhaps we could retain the tests for end-to-end testing purposes, but remove them from the CI configuration? What are your thoughts @bendeeson, @patshone-gsl?

2021-03-26 10:54 UTC, elliotmassen commented on src/Conversation/DataClients/Serializers/ApiTurnNormalizer.php
> +                    if ($type === 'RESPONSE') {
It would be worth updating these strings to use the constants.

2021-03-26 10:54 UTC, elliotmassen commented on src/Conversation/DataClients/ConversationDataClient.php
> +        ];
For readability it would be good to make this array have one object instantiation per line.

2021-03-26 10:54 UTC, elliotmassen commented on src/Conversation/DataClients/ConversationDataClient.php
> +     * @param  bool  $shallow
I wonder if it's worth removing all the `$shallow` parameters for now considering they are not used. I can imagine there's a chance they may end up hanging around long enough to cause confusion eventually 😂

2021-03-26 10:54 UTC, elliotmassen commented on src/Conversation/DataClients/Serializers/ConversationObjectNormalizer.php
> +            $object->setConditions(new ConditionCollection());
Is this something that still needs to be implemented?

2021-03-26 10:54 UTC, elliotmassen commented on src/ConversationEngine/Tests/IncomingIntentMatcherTest.php
> +    }
What's the significance of this addition? This testcase mocks out the various selectors so that graph client should not never be used.

2021-03-26 13:53 UTC, bendeeson commented
@elliotmassen In regards to https://github.com/opendialogai/core/pull/454#pullrequestreview-621985247
The benefit of having the ConversationDataClient tests talk to GraphQL is that we get failing tests in the case that we change the GraphQL schema (because the query strings would no longer be valid).

Perhaps the ideal solution would be to Mock the responses from GraphQL for speed, and have separate tests that check that the query strings conform to the graphql schema. There is a plugin for phpstorm that shows syntax errors in source code, but it takes a while to update.

2021-03-26 16:31 UTC, istos requested changes
Epic! 😄 The biggest ask from me is to see an architecture diagram +1-page explainer of the approach so that I can then understand the code better.

2021-03-26 16:31 UTC, istos commented on src/Conversation/DataClients/Serializers/IntentNormalizer.php
> +            // TODO: Handle actions
Could you provide some more info.

2021-03-26 16:31 UTC, istos commented on src/Conversation/DataClients/Serializers/IntentNormalizer.php
> +            $intent->setSampleUtterance($data['sample_utterance']);
Any chance we could reference CONSTs for these strings.

2021-03-26 16:31 UTC, istos commented on src/Conversation/DataClients/Serializers/SceneNormalizer.php
> +                // We have already loaded the conversations.
Do we need this?

2021-03-26 16:31 UTC, istos commented on src/Conversation/DataClients/Tests/ConditionSerializationTest.php
> +        /* TODO: Update when conditions can be serialized */
Is this still valid, what's the background to this?

2021-03-30 11:25 UTC, bendeeson commented on src/Conversation/Behavior.php
> +    const FIELDS = [self::BEHAVIOR];
Fields are the names of the serializable properties of an object. So maybe 'serializableProperties' would be a better name.

2021-03-30 16:26 UTC, bendeeson commented on src/Conversation/DataClients/Serializers/ApiTurnNormalizer.php
> +                    if ($type === 'RESPONSE') {
Done

2021-03-30 16:26 UTC, bendeeson commented on src/Conversation/DataClients/ConversationDataClient.php
> +        ];
Done

2021-03-30 16:27 UTC, bendeeson commented on src/Conversation/DataClients/ConversationDataClient.php
> +     * @param  bool  $shallow
I've removed all the `$shallow` parameters for now. If we need them in the future they can be re-included.

2021-03-30 16:30 UTC, bendeeson commented on src/ConversationEngine/Tests/IncomingIntentMatcherTest.php
> +    }
This was a mistake. I have removed this.

2021-03-30 16:31 UTC, bendeeson commented on src/Conversation/Conversation.php
> +     * Create a partially hydrated Scene.
I've added a couple of drafts to GitBook here: 

https://app.gitbook.com/@opendialog/s/opendialog-architecture/~/drafts/-MX2QE-2qFsQwwxAEx2C/partial-conversation-objects-hydration/@drafts

There is one page on serialization, and one on hydration. Let me know what you think.

2021-03-31 11:59 UTC, merged