Interpreter configuration
opendialogai/core pull request #486
Opened 2021-05-13 12:21 UTC by elliotmassen

This PR introduces the concept of the `ComponentConfiguration`, which provides the ability to store configuration for a component in the database. This is used concretely to populate `InterpreterConfiguration` objects. Each interpreter provides it's own subclass of `InterpreterConfiguration`, which populates its properties from the given configuration array, and more important can specify which fields are required for the interpreter to function as expected.

This PR lays the groundwork for API's to be created for management of the configurations, a subsequent PR will be published that covers the conversation engine integration of this work.

2021-05-17 15:24 UTC, stu-greenshoots requested changes
This looks great to me, really like the implementation.

I have left a couple of comments - with the Dialogflow set up, I probably just don't understand how that works!

2021-05-17 15:24 UTC, stu-greenshoots commented on src/InterpreterEngine/Configuration/InterpreterConfiguration.php
> +    public function __construct(string $name, array $data);
I'm not sure we want a constructor in an interface in this way as it removes the flexibility of an implementation. It's also discouraged by PHP:
https://www.php.net/manual/en/language.oop5.interfaces.php

Does this method have overlap with the static create method?

2021-05-17 15:24 UTC, stu-greenshoots commented on src/InterpreterEngine/Dialogflow/DialogflowInterpreterConfiguration.php
> +        self::APP_URL,
How is the `KEY` used in this configuration? I would assume it needs one similar to LUIS / QnA

2021-05-17 15:28 UTC, elliotmassen commented on src/InterpreterEngine/Configuration/InterpreterConfiguration.php
> +    public function __construct(string $name, array $data);
Ah yes, good point - I think I can do away with the signature here and keep the method in the abstract class for re-use.

2021-05-17 15:31 UTC, elliotmassen commented on src/InterpreterEngine/Dialogflow/DialogflowInterpreterConfiguration.php
> +        self::APP_URL,
I'll be changing this specific configuration class shortly actually. The Dialogflow integration, that I brought into core recently, is in fact an integration for use with a proxy lambda function (which gave us support for Dialogflow Knowledge Bases - as the PHP library doesn't yet support them). The integration (& configuration) will need updating, which will in turn introduce the key here, good spot!

2021-05-24 13:49 UTC, stu-greenshoots approved these changes

2021-05-24 15:21 UTC, merged