Adds InferredCompositeAction and tests
opendialogai/core pull request #653
Opened 2022-07-18 16:04 UTC by goranambar

Adds InferredCompositeAction and tests.

2022-07-19 17:23 UTC, elliotmassen requested changes
This is looking great Goran, thanks for all your hard work on this! I think there's just a few remaining bits to resolve, please see my comments below.

Also I think we will need a small related by in the application to update `UserContextController.formatAttributes` to ensure that composite attributes don't crash the `/contexts` endpoint.

2022-07-19 17:23 UTC, elliotmassen commented on src/AttributeEngine/Attributes/InferredCompositeAttribute.php
> +            parent::__construct($id, $value->getAttributes());
I'm not sure I understand what this does - is this related the issue regarding the value of a composite being itself?

2022-07-19 17:23 UTC, elliotmassen commented on src/AttributeEngine/Attributes/Collections/CompositeCollectionAttribute.php
> +        return InferredCompositeAttribute::class;
I think we'll want this to be `BasicCompositeAttribute` instead to get the collection agnostic to the specific type of composite it holds. Otherwise we'll need a new composite collection class for each type of composite.

2022-07-20 07:58 UTC, goranambar commented on src/AttributeEngine/Attributes/Collections/CompositeCollectionAttribute.php
> +        return implode(',', $valuesToString);
BasicCompositeAttribute `toString` already renders this to JSON:
https://github.com/opendialogai/core/blob/e3819106e41bec82513ea1221199270bd3f19e01/src/AttributeEngine/Attributes/BasicCompositeAttribute.php#L19

2022-07-20 09:03 UTC, goranambar commented on src/AttributeEngine/Attributes/InferredCompositeAttribute.php
> +            new DateTime('@' . $value);
Yes, it will render it as timestamp. Will remove it.

2022-07-20 14:29 UTC, goranambar commented
@elliotmassen  In `UserControllers::formatAttributes` we will want something like this? 
```php
$formatted = [];
        foreach ($attributes as $key => $values) {
            if (!in_array($key, self::$ignoreList)) {
                if ($values instanceof CompositeCollectionAttribute) {
                    $formatted[$key] = $values->toString();
                } else if ($values instanceof CollectionAttribute) {
                    $formatted[$key] = array_map(fn (AttributeValue $v) => $v->getRawValue(), $values->getValue());
                } else {
                    $formatted[$key] = $values->getAttributeValue()->getRawValue();
                }
            }
        }
```

2022-07-21 09:59 UTC, elliotmassen approved these changes

2022-07-21 09:59 UTC, merged