Handle case when users have the underlying scenario they are interact…
opendialogai/core pull request #683
Opened 2022-11-23 11:08 UTC by Lintume

…ing with changed.
The decision requires CORE WebchatInitController, from where the history of the chat is loaded. 
The thing is, to history endpoint has not passed the current scenario id (or alias) (only passed user_id) so we have no ability to understand, whether should we load clear history if the scenario was changed for this user or old history.
I guess we need to change the frontend code, it needs to send a scenario too for a correct understanding of what the content of history needs to be shown.
But I don't know what it can influence.

2022-11-23 16:51 UTC, elliotmassen requested changes
This looks great - and works just as expected! Thanks so much for this 👍 

Would you be able to add two tests to `ConversationalStateReasonerTest`? It would be great to have one to test the output when the scenario ID's match, and another to test when they don't.

2022-11-23 16:51 UTC, elliotmassen commented on src/ConversationEngine/Reasoners/ConversationalStateReasoner.php
> +                $currentScenarioId = $utterance->getScenarioId();
As this method is called after we've established the user, and loaded the User Context, I think we'd be fine to replace this with something like the following. This means the new `$utterance` parameter could be removed.

```suggestion
                $currentScenarioId = ContextService::getAttributeValue('selected_scenario', UserContext::getComponentId());
```

2022-11-24 12:43 UTC, Lintume commented on src/ConversationEngine/Reasoners/ConversationalStateReasoner.php
> +                $currentScenarioId = $utterance->getScenarioId();
thanks, fixed

2022-11-24 13:20 UTC, elliotmassen approved these changes

2022-11-24 14:44 UTC, merged