ODTR-23 | Scenario supported languages
opendialogai/core pull request #690
Opened 2022-12-16 15:39 UTC by goranambar

Adds support for `base language` and `supported languages` for `Scenario`. Updates the data clients to store and retrieve the languages properties of the `Scenario`

2022-12-29 14:55 UTC, stu-greenshoots requested changes
Thanks Goran, I tested this and it looks good to me. Just a couple of very small comments for you to look at

2022-12-29 14:55 UTC, stu-greenshoots commented on src/Conversation/Scenario.php
> +    public function getSupportedLanguages(): ?array
I guess this would always return an array as it is initialised?

2022-12-29 14:55 UTC, stu-greenshoots commented on src/CoreServiceProvider.php
> +        $this->app->singleton(TranslateServiceInterface::class, function () {
A small change, but could we create a TranslateServiceProvider as per the other modules? Just to keep everything together. 
Eg the ActionEngineServiceProvider

2022-12-29 16:14 UTC, goranambar commented on src/Conversation/Scenario.php
> +    public function getSupportedLanguages(): ?array
Hey @stu-greenshoots this is simillar as `status` and `active`, which are both `nullable` and can be set to null in  [dehydrate](https://github.com/opendialogai/core/blob/14cf399f6173ab66f3e4adcfa6b5b684fb83483d/src/Conversation/Scenario.php#L48).

2023-01-04 16:07 UTC, stu-greenshoots approved these changes

2023-01-04 16:08 UTC, merged