Feature/conversation engine functional tests
opendialogai/core pull request #691
Opened 2022-12-19 14:03 UTC by Lintume

First rude stage of writing tests. Tests are workable but look like noodles.

[Task in Jira](https://opendialog.atlassian.net/jira/software/projects/OPNDLG/boards/13?assignee=6318527c09bc6014ea8c8e37&selectedIssue=OPNDLG-1775)

2022-12-20 16:22 UTC, elliotmassen requested changes
This is looking good Lialia 🏆  Really great work!

Please see my suggestions below. If possible, I think it would be worth addressing these separately from the optimisation phase. This would mean that we give ourselves the ability to merge this iteration of the tests without blocking ourselves while we iron out the (potentially tricky) work of optimising them for readability / maintainability.

2022-12-20 16:22 UTC, elliotmassen commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +         * 2. Given a intent.core.welcome (callback / button response) utterance, for an existing user,
I think it will be worth exploring how we can chunk each of these cases up into a separate test method as part of this first phase. That way we have created a way to test from any position in the scenario without having to have previously run the conversation engine. I think this should be possible by artificially giving a user a "user history record" of the desired state.

2022-12-20 16:22 UTC, elliotmassen commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +        )->getValue());
Great idea 👍

2022-12-20 16:22 UTC, elliotmassen commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +        $user->setRootId('utterance_user');
It's worth using the constant here instead:

```suggestion
        $user->setRootId(UtteranceAttribute::UTTERANCE_USER);
```

2022-12-20 16:45 UTC, Lintume commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +         * 2. Given a intent.core.welcome (callback / button response) utterance, for an existing user,
I thought separating every test case independently I'll leave for the next phase, but ok :)

2022-12-20 21:09 UTC, Lintume commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +        $user->setRootId('utterance_user');
fixed

2022-12-23 10:10 UTC, elliotmassen approved these changes

2023-01-09 08:46 UTC, merged