OPNDLG-1777 conversation engine functional tests improving
opendialogai/core pull request #693
Opened 2023-01-03 18:12 UTC by Lintume

[Task in Jira](https://opendialog.atlassian.net/jira/software/projects/OPNDLG/boards/13?assignee=6318527c09bc6014ea8c8e37&selectedIssue=OPNDLG-1777)

2023-01-09 12:51 UTC, elliotmassen requested changes
This is really great! It's so nice to see how easy to read those tests are now 👍 

Please see my comments below. The majority are centred around ensuring that the naming of the public methods is clear for others who use these classes.

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +            $this->fail('Be sure that you run mandatory initializeScenario() for $scenarioTestBuilder object');
Should this use `$this->testCase->fail` instead?

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +class ConversationEngineTestBuilder extends TestCase
Does this need to extend `TestCase` if we use have the `$this->testCase` property?

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public function userSaid($utteranceOrText): ConversationEngineTestBuilder
What do you think about how to name this method? I'm wondering if they'd be best in present tense, like follows.

```suggestion
    public function userSays($utteranceOrText): ConversationEngineTestBuilder
```

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public ?string $answerIntentOdId;
I think it'd be worth making these properties protected, so that we have to be intentional about which ones we want to allow for getting/setting.

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public function runConversationEngine()
Let's rename this method to simply be: `run`. Also, would you be able to add the return type to the method signature please?

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public function withUserState(ConversationalState $state): ConversationEngineTestBuilder
What do you think about renaming this to the following?

```suggestion
    public function withConversationalState(ConversationalState $state): ConversationEngineTestBuilder
```

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +    public function __construct(TestCase $testCase)
Would this class work is `$testCase` was type `TestCase`? It looks as though perhaps we want to be stricter with the parameter type to be `ConversationEngineTestBuilder`.

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +            $this->testCase->assertNotEquals(MessageTemplateMatcher::ERROR_MESSAGE_ID, $message->getOdId());
Let's add an assertion message here, so that if the assertion fails that it's clear what's happened.

2023-01-09 12:51 UTC, elliotmassen commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +    public function assertChatAnswer(string $intentOdId): ScenarioAssertionsBuilder
I think we should rename this as follows:

```suggestion
    public function assertResponseContainsMessage(string $intentOdId): ScenarioAssertionsBuilder
```

2023-01-09 15:37 UTC, Lintume commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +        $this->conversationEngine = resolve(ConversationEngineInterface::class);
It creates new instance without forgetInstance, it's enough to resolve :)

2023-01-09 15:39 UTC, Lintume commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +    public bool $isAssertStates = false;
no, I'll change it to private

2023-01-09 15:46 UTC, Lintume commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +        }
`assertStates()` it's the shortest way to check all states. For checking outcome state is required chat answer intent, that is argument in `assertChatAnswer(string $intentOdId)`. I added the flag `isAssertStates` for the ability to add assertions in any order. so, if `assertChatAnswer()` is added to the chain of assertions after `assertStates()` it will perform assertion states directly in the `assertChatAnswer` function. any suggestions to make it clearer are welcome :)

2023-01-09 15:56 UTC, Lintume commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +            $this->fail('Be sure that you run mandatory initializeScenario() for $scenarioTestBuilder object');
no, as soon as [ConversationEngineFunctionalTest.php](https://github.com/opendialogai/core/pull/693/files/e4b6325ca75997d24f58a258638c2261e650d5e2#diff-3ccd99e2ebf14efe93de2af102a9f02586b1b27e0ea6e100aadf2cb9e8358c84) extends TestCase we no need to call it by testCase property, Moreover, we have no such property in this class (we no need it)

2023-01-09 16:05 UTC, Lintume commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public function chatShouldHearIntent($interpretedIntents): ConversationEngineTestBuilder
yes, agree, looks better :)

2023-01-09 16:07 UTC, Lintume commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public ?string $answerIntentOdId;
I thought about setters/getters for protected properties, I'll add them

2023-01-09 16:22 UTC, Lintume commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public function runConversationEngine()
`run` function already used in TestCase class.
also, this method can return $this or void, but in PHP 7.4 this syntax is not allowed

2023-01-09 16:29 UTC, Lintume commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public function withUserState(ConversationalState $state): ConversationEngineTestBuilder
hmmm... This new name has not reflected the condition of the 'existing user' in the test case. For example, 
"GIVEN Existing user with state after welcome message..."
Here we have the condition of the existing user. I understand that existing user are defined by conversation state, but from the point of intelligibility... what do you think?

2023-01-09 16:37 UTC, Lintume commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +    public function __construct(TestCase $testCase)
yes, agree, thanks

2023-01-09 16:42 UTC, Lintume commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +            $this->testCase->assertNotEquals(MessageTemplateMatcher::ERROR_MESSAGE_ID, $message->getOdId());
oki

2023-01-09 16:44 UTC, Lintume commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +    public function assertChatAnswer(string $intentOdId): ScenarioAssertionsBuilder
oki :)

2023-01-12 09:32 UTC, elliotmassen commented on Tests/Utils/Builders/ScenarioAssertionsBuilder.php
> +        }
Ah I see, thanks for clarifying! I think it's fine as it for now 👍

2023-01-12 09:34 UTC, elliotmassen commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public function runConversationEngine()
Ah good point - my bad! No worries, let's leave it as is 👍

2023-01-12 09:43 UTC, elliotmassen commented on Tests/Utils/Builders/ConversationEngineTestBuilder.php
> +    public function withUserState(ConversationalState $state): ConversationEngineTestBuilder
That's a fair point - I get what you mean. However, my thinking was that "with user state" potentially implies that there is some other kind of state (i.e. "with app state"). Currently there is only conversational state that is owned by a user (in user history record), however these state objects can also represent states relative to both the user and the application. I think it might be confusing for someone to see a `$state` with a speaker of `Intent::APP`, but then to see that state passed to a `withUserState` method.

Let me know what you think!

2023-01-13 12:15 UTC, Lintume commented on src/Conversation/DataClients/Relational/ConversationDataClient.php
> +        $intentModel = ConversationObjectBase::where('od_id', $intentOdId)->first();
yes, agree, I'll add checking type and scenario

2023-01-13 12:16 UTC, Lintume commented on src/Conversation/DataClients/Relational/ConversationDataClient.php
> +    public function getIntentByOdId(string $intentOdId): Intent
totally agree :)

2023-01-24 11:22 UTC, elliotmassen requested changes
Thanks for making those changes, and including the complex tests. I think the comments above each test case are super useful, thank you for including them 👍  Just a few further comments.

2023-01-24 11:22 UTC, elliotmassen commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +            ->assertIncomingIntentState($scenarioTestBuilder->getStateFromIntent('helpRequest'))
Is there anyway we are able to make an assertion about both incoming states (the one before virtual intent, and the one after)? If so, it'd be worth looking to do the same for the outgoing and message template states too.

2023-01-24 11:22 UTC, elliotmassen commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +                ->setConversationSystem(null)) // Event of changing Message Template State firing before Conversation System changing
Ah that's a good spot - I didn't realise this!

It makes me wonder if we should update the `ConversationEngine.processMessageTemplate` method so that the state is manipulated before we fire the event. That way it would be consistent with the `ConversationEngine.updateState` method, where the state is created from the intent (including any transition / completing behaviour manipulations). What do you think? Perhaps we would need to consider if that might break any existing functionality.

2023-01-24 11:22 UTC, elliotmassen commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +        ]);
It's worth noting that this slightly different from what we had discussed, however it does still test dynamic transitioning - so it's not incorrect at all!

The state that is being generated from that `moreInfoRequest` creates a `MID_TURN` state. This means that when the action is run, we update the conversational position to the middle of that turn (as if we had just matched `moreInfoRequest` intent). We haven't previously used dynamic transitions like this, but it's very cool to see that this is possible!

In order to keep the test more straightforward, I think it would be worth using a state for the Welcome turn, with the status of `IN_TURN`. This would model a dynamic (turn) transition. The Welcome turn has an application request intent, so the cadence is already as you required. You would be able to easily get this state by using `getStateFromIntent` on the `intent.core.welcome` intent in the Trigger conversation I think.

2023-01-24 12:04 UTC, Lintume commented on src/Conversation/DataClients/Relational/IntentDataClient.php
> +    public function getIntentByOdId(string $intentOdId, string $scenarioUid): IntentCollection
ah, sorry, my bad, thanks, I'll add it

2023-01-26 10:54 UTC, Lintume commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +            ->assertIncomingIntentState($scenarioTestBuilder->getStateFromIntent('helpRequest'))
I've added ability to check all states changing.

2023-01-26 10:56 UTC, Lintume commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +                ->setConversationSystem(null)) // Event of changing Message Template State firing before Conversation System changing
I've changed `ConversationEngine.processMessageTemplate` in a way that the template status updating after the conversation system change

2023-01-26 10:56 UTC, Lintume commented on Tests/Feature/ConversationEngineFunctionalTest.php
> +        ]);
I hope I've done this :)

2023-01-26 12:13 UTC, elliotmassen approved these changes
This is really great! 🏆 Thanks for making these changes - I'm happy for this to be merged.

2023-01-30 12:24 UTC, merged