ODTR 56 | Add message translation helper
opendialogai/core pull request #708
Opened 2023-02-07 16:31 UTC by goranambar

Adds message translation helper that strips all of the translatable content from Template messages and adds it to the translation table.

2023-02-08 17:39 UTC, oliversarfas requested changes
Great PR @goranambar, looks great and nice test coverage.

Could we add a test for when the translation is not found that we return the original value requested? Doesn't have to be for each message type, just a basic proof of concept that it works should suffice as we have tests for the rest already

2023-02-08 17:39 UTC, oliversarfas commented on src/CoreServiceProvider.php
> +            StripScenariosTranslatableStrings::class
Minor thing, add trailing comma to make next update cleaner in git diff

```suggestion
            StripScenariosTranslatableStrings::class,
```

2023-02-08 17:39 UTC, oliversarfas commented on src/Translate/Helpers/ComponentConfigurationTranslationHelper.php
> +                // TODO: should we revert to the base language here, if there's no translation with the
I prefer the way you've got it already. If a user asks for translation in 'es' but we don't have it, return their original value. If we defaulted to 'jp' or something, it'd be confusing

2023-02-08 17:39 UTC, oliversarfas commented on src/Translate/Helpers/MessageTemplateTranslationHelper.php
> +                    break;
Can we run $messageCount++ after the switch? Seems unnecessary to have it in each case

2023-02-09 09:45 UTC, goranambar commented on src/Translate/Helpers/ComponentConfigurationTranslationHelper.php
> +                // TODO: should we revert to the base language here, if there's no translation with the
Falling back to base language is a requirement by design, @oliversarfas . Just not sure at the moment if we should do it in this place.

2023-02-09 09:47 UTC, goranambar commented on src/Translate/Helpers/MessageTemplateTranslationHelper.php
> +                    break;
@oliversarfas not all messages have translatable content and we want to count only the ones that do.

2023-02-09 11:07 UTC, goranambar commented
Thanks @oliversarfas . Those tests you required were actually from [previous approved PR](https://github.com/opendialogai/core/pull/704) :) But I have added them here, nonetheless. Sorry for the confusion.

2023-02-13 16:17 UTC, oliversarfas approved these changes

2023-02-16 09:29 UTC, merged