Adds forceUpdate to ComponentConfigurationTranslationHelper
opendialogai/core pull request #709
Opened 2023-02-10 12:07 UTC by oliversarfas

add boolean to allow for bypas of update and return existing string instead

2023-02-10 12:51 UTC, goranambar requested changes
Hey @oliversarfas I'm afraid this is not what we're looking for. I dropped some directions on how to implement this.

2023-02-10 13:18 UTC, goranambar requested changes
Still couple of points to fix.

2023-02-10 13:18 UTC, goranambar commented on src/Translate/Services/TranslateService.php
> +        if ($forceUpdate) {
So, if `$forceUpdate` is set to `false`, and `LanguageLine` didn't exist previously (as it is created few lines before), it won't set the translation string to it. And we don't want that, right?

2023-02-10 13:18 UTC, goranambar commented on src/Translate/Services/TranslateService.php
>          if (!$languageLine) {
Just check before this line:
`if ($languageLine && !$forceUpdate){return;}`
And delete the `$forceUpdate` check below.

2023-02-10 13:28 UTC, goranambar commented on src/Translate/Services/TranslateService.php
> +        bool $forceUpdate,
This should be not in here but in `addOrUpdateConfigTranslation` right?

2023-02-10 13:29 UTC, goranambar commented on src/Translate/Services/TranslateServiceInterface.php
> +        bool $forceUpdate,
This should be not in here but in addOrUpdateConfigTranslation right?

2023-02-10 13:39 UTC, oliversarfas commented
@goranambar test added and PR feedback actioned

2023-02-14 12:29 UTC, goranambar approved these changes
Looks OK now

2023-02-16 09:37 UTC, merged