Feature/mova 162
opendialogai/core pull request #715
Opened 2023-02-17 10:28 UTC by andrii-movadex

2023-02-21 17:21 UTC, elliotmassen requested changes
- [ ] Would you be able to ensure that these PR's have titles which reflect the changes they include?
- [ ] Let's get some tests added for this service.
- [ ] Please could you ensure that these classes live within a `LanguageServiceEngine` directory and namespace.

2023-02-21 17:21 UTC, elliotmassen commented on src/Components/Helper/ComponentHelper.php
> +    const NLU_ID_PATTERN = "/^language_service\core*\.[A-z_]*$/";
Let's update this constant name to be as clear as possible.

```suggestion
    const LANGUAGE_SERVICE_ID_PATTERN = "/^language_service\core*\.[A-z_]*$/";
```

2023-02-21 17:21 UTC, elliotmassen commented on src/NluEngine/Component/NluComponentInterface.php
> +namespace OpenDialogAi\NluEngine\Component;
These classes should all live in a new Language Service namespace and directory. The NLU Engine is a different (outdated) engine.

2023-02-21 17:21 UTC, elliotmassen commented on src/NluEngine/Component/NluComponentInterface.php
> +interface NluComponentInterface
Let's rename these classes after "LanguageService" rather than "Nlu".

```suggestion
interface LanguageServiceComponentInterface
```

2023-02-21 17:21 UTC, elliotmassen commented on src/NluEngine/Service/NluComponentService.php
> +        $id = $class::getComponentId();
I think it would be worth adding a call to `$class::getComponentData()` above this line (like the Interpreter Engine) so that we are able to throw any errors related to incorrect set up of component classes (i.e. `MissingRequiredComponentDataException` from unset ID, type or source.

2023-02-21 17:21 UTC, elliotmassen commented on src/NluEngine/Component/NluComponentInterface.php
> +    public function interpret(UtteranceAttribute $utterance) : ResponseInterface;
As per the Interpreter component service interface, we will also need a signature for `getConfiguration`, `createConfiguration`, and `getDefaultConfigurationData` in this interface.

2023-02-21 17:21 UTC, elliotmassen commented on src/NluEngine/Service/NluComponentService.php
> +     * @var Map|InterpreterInterface[]
Could you correct the doc blocks please?

2023-02-27 16:51 UTC, elliotmassen requested changes
Thanks for making those changes Andrii! Just a few comments below:

- [ ] As requested in the last review, would you be able to ensure that these PR's have titles which reflect the changes they include?
- [ ] Would you be able to update the directory, namespace and classes to be `LanguageProcessor` rather than `LanguageService`? Apologies for the second change to this, however we have taken a decision that all backend references to "Language Services" would be clearer if we refer to them as "Language Processors" - the frontend will still refer to them as Services however (it's simply a way to make it easier for us to talk about them in the backend).

2023-02-27 16:51 UTC, elliotmassen commented on src/LanguageServiceEngine/Service/LanguageServiceComponentServiceInterface.php
> +    public function register(string $class): void;
Let's add a `@throws` comment here to document that this method can throw `MissingRequiredComponentDataException`.

2023-02-27 16:51 UTC, elliotmassen commented on src/LanguageServiceEngine/Component/LanguageServiceComponentInterface.php
> +     * @throws AbstractNLURequestFailedException
Should this be here?

2023-02-27 16:55 UTC, elliotmassen commented on src/LanguageServiceEngine/Configuration/BaseLanguageServiceConfiguration.php
> +class BaseLanguageServiceConfiguration extends BaseConfiguration implements LanguageServiceConfigurationInterface
Does this class need to override `getConfigurationKey` or similar in order to account for the fact that the key won't contain a scenario ID? Currently the key's have a non-nullable `scenarioId` property. I think we should explicitly account for this (rather than providing empty string as scenario ID).

2023-02-28 14:03 UTC, andrii-movadex commented on src/LanguageServiceEngine/Service/LanguageServiceComponentServiceInterface.php
> +    public function register(string $class): void;
Fixed.

2023-02-28 14:04 UTC, andrii-movadex commented on src/LanguageServiceEngine/Component/LanguageServiceComponentInterface.php
> +     * @throws AbstractNLURequestFailedException
Fixed.

2023-02-28 14:25 UTC, andrii-movadex commented on src/LanguageServiceEngine/Configuration/BaseLanguageServiceConfiguration.php
> +class BaseLanguageServiceConfiguration extends BaseConfiguration implements LanguageServiceConfigurationInterface
I've added LanguageProcessorConfigurationKey and overrided getConfigurationKey method inside BaseLanguageProcessorConfiguration class. I am not sure this is the best solution but the other way is to update getConfigurationKey inside BaseConfiguration file to accept nullable values also. Please check

2023-03-02 16:58 UTC, elliotmassen requested changes
Thanks for making those changes! A few final comments below.

2023-03-02 16:58 UTC, elliotmassen commented on src/Components/Helper/ComponentHelper.php
> +    const LANGUAGE_PROCESSOR_ID_PATTERN = "/^language_processor\.core\.[A-z_]*$/";
These component ID's can be registered with any scope, not just `core`. Let's make this consistent with the established patterns:

```suggestion
    const LANGUAGE_PROCESSOR_ID_PATTERN = "/^language_processor\.[A-z]*\.[A-z_]*$/";
```

2023-03-02 16:58 UTC, elliotmassen commented on src/LanguageServiceEngine/Configuration/BaseLanguageServiceConfiguration.php
> +class BaseLanguageServiceConfiguration extends BaseConfiguration implements LanguageServiceConfigurationInterface
Thanks Andrii! I think we might need to consider a different solution here. Currently, as the new class extends the existing one, it would still be possible to call `getScenarioId` on an object of the new class, which would cause an error currently as the `scenarioId` property is undefined.

To keep the codebase more maintainable, I think it might be worth introducing a new class like `ComponentConfigurationKeyWithName` that only contains the `configurationName` property (and associated methods), and then to make the existing `ComponentConfigurationKey` class extend this new class. This way we can use the new `ComponentConfigurationKeyWithName` to key the Language Processors. The new inheritance chain would be:

`Hashable` -> `ComponentConfigurationKeyWithName` -> `ComponentConfigurationKey`

2023-03-09 11:35 UTC, elliotmassen approved these changes

2023-03-09 11:40 UTC, merged