Feature/mova 163
opendialogai/core pull request #716
Opened 2023-02-17 15:37 UTC by andrii-movadex

2023-02-21 17:21 UTC, elliotmassen requested changes
Alongside my feedback given in https://github.com/opendialogai/core/pull/715#pullrequestreview-1307842326, could you add some tests for this too please?

I also think it would be worth adding an abstract class similar to `BaseInterpreter`.

2023-02-27 17:01 UTC, elliotmassen requested changes

2023-02-27 17:01 UTC, elliotmassen commented on src/LanguageServiceEngine/Tests/Helper/HelperToProvideLanguageServices.php
> +    public function provideConfiguredLanguageServiceService(Application $app, LanguageServiceComponentServiceInterface $languageServiceComponentService)
Do we need this method? I'm thinking that this should be happening anyway in a service provider.

2023-02-27 17:01 UTC, elliotmassen commented on src/Components/ODComponentTypes.php
> +    const LANGUAGE_SERVICE_COMPONENT_TYPE = 'language_service';
Let's get this updated to:

```suggestion
    const LANGUAGE_PROCESSOR_COMPONENT_TYPE = 'language_processor';
```

2023-02-28 16:00 UTC, andrii-movadex commented on src/LanguageServiceEngine/Tests/Service/ConfiguredLanguageServiceServiceTest.php
> +    }
Yes, removed it.

2023-02-28 16:03 UTC, andrii-movadex commented on src/LanguageServiceEngine/Tests/Helper/HelperToProvideLanguageServices.php
> +    public function provideConfiguredLanguageServiceService(Application $app, LanguageServiceComponentServiceInterface $languageServiceComponentService)
yes, but there is no service provider now.. And I need somehow resolve bindings. May be I can resolve class instead of interface and it will be working. I am not sure what is the best way here

2023-03-02 17:03 UTC, elliotmassen approved these changes
Thanks for making those changes - this is looking good 👍

2023-03-03 09:52 UTC, andrii-movadex commented on src/LanguageServiceEngine/Tests/Helper/HelperToProvideLanguageServices.php
> +    public function provideConfiguredLanguageServiceService(Application $app, LanguageServiceComponentServiceInterface $languageServiceComponentService)
ok, I will tidy up this when I will setup the provider. Agreed

2023-03-09 11:42 UTC, merged