Implement language processor service (with interfaces)
opendialogai/core pull request #718
Opened 2023-02-27 15:45 UTC by andrii-movadex

2023-02-27 17:11 UTC, elliotmassen requested changes
Thanks Andrii! Please see my comments below.

2023-02-27 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Service/LanguageServiceService.php
> +class LanguageServiceService implements LanguageServiceServiceInterface
```suggestion
class LanguageProcessorService implements LanguageProcessorServiceInterface
```

2023-02-27 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Service/LanguageServiceService.php
> +    public function interpret(ComponentConfigurationKey $key, UtteranceAttribute $utterance): ResponseInterface
This is signature is exactly right, nice one 👍

2023-02-27 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Service/LanguageServiceService.php
> +            return new EmptyResponse();
I think this exception should be thrown by this method, as there is a difference between an empty response and no response.

2023-02-27 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Service/LanguageServiceService.php
> +            /** @var LanguageServiceComponentInterface $languageServiceComponent */
PhpStorm is saying that we are missing this interface as an import.

2023-03-01 14:31 UTC, andrii-movadex commented on src/LanguageServiceEngine/Response/ResponseInterface.php
> +    public function getData() : array;
Well, I added that because:
- I was thinking I would require to get some data from response and this method could be helpful
- and also to be able to add tests and check if the service working
I've removed this now because it is also possible to work without this method and according to the future response (you've provided me an example of that) there should not be such a method.

2023-03-02 17:11 UTC, elliotmassen requested changes

2023-03-02 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Service/LanguageServiceService.php
> +            return new EmptyResponse();
I think this issue is still outstanding, however just in the `LanguageProcessorService` now.

2023-03-02 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Service/LanguageServiceService.php
> +                        ));
I think this issue is still outstanding, however just in the `LanguageProcessorService` now.

2023-03-02 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Tests/Service/LanguageServiceServiceTest.php
> +    public function testLanguageServiceService()
Would you be able to update this test name to the new processor phrasing?

2023-03-02 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Tests/Service/LanguageServiceServiceTest.php
> +        $configuration = LanguageServiceModelExample::createConfiguration($name)->setConfigurationScenarioId('0x000');
I think this may need updating in line with the changes from the other PR's (re. the scenario ID, and the `LanguageServiceModelExample` class name.

2023-03-02 17:11 UTC, elliotmassen commented on src/LanguageServiceEngine/Tests/Service/LanguageServiceServiceTest.php
> +    }
Let's remove this.

2023-03-03 11:03 UTC, andrii-movadex commented on src/LanguageServiceEngine/Service/LanguageServiceService.php
> +            return new EmptyResponse();
Sorry, I am not sure I clearly understood this. So should I remove all the catch blocks?

2023-03-09 11:39 UTC, elliotmassen approved these changes

2023-03-09 11:44 UTC, merged