Add IntentClassifierConfiguration (with interfaces)
opendialogai/core pull request #720
Opened 2023-03-01 15:24 UTC by andrii-movadex

2023-03-09 11:52 UTC, elliotmassen requested changes

2023-03-09 11:52 UTC, elliotmassen commented on src/LanguageProcessorEngine/Configuration/BaseLanguageProcessorConfiguration.php
> +    }
Let's remove this setter method. Please see `InterpreterWithEntitiesConfiguration` for an example of the pattern we use for setting properties in configurations. We will expect the `type` data to be present in the `$data` parameter of the constructor of this configuration (stored in the `configuration` field on the `ComponentConfiguration` model).

2023-03-09 11:52 UTC, elliotmassen commented on src/LanguageProcessorEngine/Tests/Configuration/ConfigurationTest.php
> +class ConfigurationTest extends TestCase
Let's add a test here to check that the `type` property is successfully get/set.

2023-03-09 15:53 UTC, elliotmassen requested changes
Thanks Andrii! Just two final small tweaks to make.

2023-03-09 15:53 UTC, elliotmassen commented on src/LanguageProcessorEngine/Configuration/BaseLanguageProcessorConfiguration.php
> +    const TYPE_KEY = 'type';
Let's just call this TYPE for simplicity.

```suggestion
    const TYPE = 'type';
```

2023-03-10 11:21 UTC, elliotmassen requested changes

2023-03-10 11:21 UTC, elliotmassen commented on src/LanguageProcessorEngine/Configuration/BaseLanguageProcessorConfiguration.php
> +    protected static array $requiredAttributes = [self::TYPE];
Apologies this is my bad for not being specific enough, this wants to be the `$required` property from `BaseConfiguration`.

```suggestion
    protected static array $required = [self::TYPE];
```

2023-03-10 11:21 UTC, elliotmassen commented on src/LanguageProcessorEngine/Tests/Configuration/ConfigurationTest.php
> +        $this->expectException(ErrorException::class);
I think we'd expect `InvalidConfigurationDataException` here instead.

2023-03-10 13:33 UTC, andrii-movadex commented on src/LanguageProcessorEngine/Configuration/BaseLanguageProcessorConfiguration.php
> +    protected static array $requiredAttributes = [self::TYPE];
No worries, I also could be more attentive. Fixed.

2023-03-14 15:32 UTC, elliotmassen approved these changes

2023-03-14 15:40 UTC, merged