Feature/mova 177
opendialogai/core pull request #722
Opened 2023-03-02 16:00 UTC by andrii-movadex

2023-03-10 08:47 UTC, andrii-movadex commented on src/LanguageProcessorEngine/Response/LanguageProcessorResult.php
> +    public function __construct(IntentCollection $intents)
I've added a comment to the MOVA-161.

2023-03-10 11:24 UTC, elliotmassen requested changes

2023-03-10 11:24 UTC, elliotmassen commented on src/LanguageProcessorEngine/Component/BaseLanguageProcessor.php
> +            default => throw new OpenDialogLanguageProcessorNotFoundException()
Thanks for adding this! 👍 Would you be able to rename it to be just `LanguageProcessorNotFoundException`?

2023-03-10 11:24 UTC, elliotmassen commented on src/LanguageProcessorEngine/Component/IntentClassifierInterface.php
> +    const TYPE = 'Intent Classifer';
Let's go with:

```suggestion
    const TYPE = 'intent_classifer';
```

2023-03-14 15:33 UTC, elliotmassen approved these changes

2023-03-14 15:41 UTC, merged