Create types that define the appropriate data model
opendialogai/core pull request #726
Opened 2023-03-07 13:27 UTC by andrii-movadex

2023-03-09 15:12 UTC, elliotmassen requested changes
This looks good 👍 Just a few comments below:

 - [x] Let's move the `$casts` arrays to be just under the `$fillable` declarations.
 - [x] Could you please add class doc comments to the models to document their properties?
 - [x] Please prefix all the migration's table names with `language_processor_`. This will ensure we don't create any confusion with other internal uses of intents or utterances.

2023-03-09 15:12 UTC, elliotmassen commented on src/LanguageProcessorEngine/Model/Dataset.php
> +        return $this->belongsTo(ComponentConfiguration::class);
I wonder whether this PR should also include the inverse change to `ComponentConfiguration` to be able to optionally call query the dataset - do you think that's worth adding here?

2023-03-13 15:01 UTC, andrii-movadex commented on src/LanguageProcessorEngine/Model/Dataset.php
> +        return $this->belongsTo(ComponentConfiguration::class);
According to our communication in slack, we can leave this as it is for now. May be later if it will be required and we will add an inverse relation method. Hope it makes sense. Thanks

2023-03-14 15:46 UTC, elliotmassen requested changes
Thanks for making these changes! The migration table name changes are correct - however they are missing the respective updates to the table names referenced in the `down` methods.

2023-03-15 08:31 UTC, andrii-movadex commented
> Thanks for making these changes! The migration table name changes are correct - however they are missing the respective updates to the table names referenced in the down methods.

Sorry for that. Fixed

2023-03-15 10:48 UTC, elliotmassen approved these changes

2023-03-15 10:49 UTC, merged