Connect new Language service engine to the SAAS app via Reflection
opendialogai/core pull request #727
Opened 2023-03-07 16:36 UTC by andrii-movadex

…lving of LanguageProcessorEngineReflectionInterface (inside ReflectionServiceProvider); ADDED resolving of LanguageProcessorEngineReflectionInterface inside ReflectionHelper; ADDED test.

2023-03-09 13:24 UTC, elliotmassen requested changes
Thanks Andrii, this is really great! This will also require a sibling PR in the application in order to return this data from the reflection endpoint.

Would you also be able to add a test like `testGetAvailableConfiguredLanguageProcessors` to test this aspect of the reflection too?

2023-03-09 13:24 UTC, elliotmassen commented on src/Reflection/Reflections/LanguageProcessorEngineReflection.php
> +                'language_processor_data' => [
Let's also add in a `types` field here that specifies the types this processor provides.

2023-03-09 13:24 UTC, elliotmassen commented on src/Reflection/Reflections/LanguageProcessorEngineReflection.php
> +        ];
I think it would be worth adding a `engine_configuration` field here (see how we do this in `InterpreterEngineReflection` for an example). This engine configuration should iterate through each of the registered processor components, create an array of all their provided types (via `getTypes`), and then return an array of unique types. This will provide the front-end with a unique list of types to offer to the user.

2023-03-13 14:28 UTC, andrii-movadex commented
> Thanks Andrii, this is really great! This will also require a sibling PR in the application in order to return this data from the reflection endpoint.
> 
> Would you also be able to add a test like `testGetAvailableConfiguredLanguageProcessors` to test this aspect of the reflection too?

I've created a PR https://github.com/movadex/opendialog-saas/pull/3 for this task in saas project. Please check.
Also I've added mentioned test to core project. Please check.

2023-03-15 10:50 UTC, merged